---

- name: Install basic packages
  become: true
  ansible.builtin.package:
    name:
      - base-devel
      - git
      - wget
      - curl
      - less
      - net-tools
      - man-db
      - man-pages
      - man-pages-fr
      - btop
      - python-pipx
    state: present
